"""Add RBAC tables and relationships

Revision ID: 059ea706839b
Revises: 99469a5de83e
Create Date: 2026-03-26 13:10:53.487700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '059ea706839b'
down_revision: Union[str, Sequence[str], None] = '99469a5de83e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_index(op.f('idx_audit_logs_company_created'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_entity'), table_name='audit_logs')
    op.create_index('idx_audit_logs_company_entity', 'audit_logs', ['company_id', 'entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('idx_companies_status'), table_name='companies')
    op.drop_constraint(op.f('contracts_company_employee_uk'), 'contracts', type_='unique')
    op.drop_index(op.f('idx_contracts_company_department'), table_name='contracts')
    op.create_index('idx_contracts_company', 'contracts', ['company_id'], unique=False)
    op.create_index('idx_contracts_employee', 'contracts', ['employee_id'], unique=False)
    op.drop_constraint(op.f('contracts_employee_id_fkey'), 'contracts', type_='foreignkey')
    op.create_foreign_key(None, 'contracts', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('idx_otp_tokens_phone_expires'), table_name='otp_tokens')
    op.create_index('idx_otp_tokens_user_expires', 'otp_tokens', ['user_id', 'expires_at'], unique=False)
    op.alter_column('payslip_upload_rows', 'error_message',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_constraint(op.f('payslip_upload_sessions_upload_session_id_key'), 'payslip_upload_sessions', type_='unique')
    # Note: Self-referencing FK on upload_session_id removed - not part of RBAC changes
    op.alter_column('payslips', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('user_company_roles', 'role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index(op.f('idx_user_company_roles_role'), table_name='user_company_roles')
    op.drop_constraint(op.f('user_company_roles_user_company_uk'), 'user_company_roles', type_='unique')
    op.create_unique_constraint('user_company_roles_uk', 'user_company_roles', ['user_id', 'company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_company_roles_uk', 'user_company_roles', type_='unique')
    op.create_unique_constraint(op.f('user_company_roles_user_company_uk'), 'user_company_roles', ['user_id', 'company_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_user_company_roles_role'), 'user_company_roles', ['role', 'company_id'], unique=False)
    op.alter_column('user_company_roles', 'role',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('payslips', 'notes',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    # Note: Self-referencing FK on upload_session_id removed - not part of RBAC changes
    op.create_unique_constraint(op.f('payslip_upload_sessions_upload_session_id_key'), 'payslip_upload_sessions', ['upload_session_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('payslip_upload_rows', 'error_message',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index('idx_otp_tokens_user_expires', table_name='otp_tokens')
    op.create_index(op.f('idx_otp_tokens_phone_expires'), 'otp_tokens', ['phone', 'expires_at'], unique=False)
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.create_foreign_key(op.f('contracts_employee_id_fkey'), 'contracts', 'employees', ['employee_id'], ['id'], ondelete='RESTRICT')
    op.drop_index('idx_contracts_employee', table_name='contracts')
    op.drop_index('idx_contracts_company', table_name='contracts')
    op.create_index(op.f('idx_contracts_company_department'), 'contracts', ['company_id', 'department'], unique=False)
    op.create_unique_constraint(op.f('contracts_company_employee_uk'), 'contracts', ['company_id', 'employee_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_companies_status'), 'companies', ['status'], unique=False)
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index('idx_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('idx_audit_logs_company_entity', table_name='audit_logs')
    op.create_index(op.f('idx_audit_logs_entity'), 'audit_logs', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_audit_logs_company_created'), 'audit_logs', ['company_id', 'created_at'], unique=False)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=45),
               existing_nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
